version: "2.4"
services:
  wordpress:
    image: wordpress:5.7.1-apache
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db
  db:
    image: mysql:8.0.19
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=wordpress_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
