version: "3.0"
services:
  web:
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./conf:/etc/nginx/templates
    environment:
      - NGINX_PORT=8080
    ports:
      - 8888:8080
