version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates/
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: flask
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      - mongo

  mongo:
    image: mongo
