volumes:
  gitlab-conf: ~
  gitlab-logs: ~
  gitlab-data: ~
  runner-conf: ~
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      EXTERNAL_URL: 'http://localhost'
      GITLAB_ROOT_EMAIL: 'root@local'
      GITLAB_ROOT_PASSWORD: 'supersecret'
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: ''
      ENABLE_BOOTSNAP: ''
      # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab-conf:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    shm_size: '256m'
  runner:
    image:  gitlab/gitlab-runner:latest
    volumes:
      - runner-conf:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
