volumes:
  gitlab-conf: ~
  gitlab-logs: ~
  gitlab-data: ~
  runner-conf: ~
  registry_data: ~


services:
  web:
    image: 'gitlab/gitlab-ee:16.10.4-ee.0'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      ENABLE_BOOTSNAP: "1"
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424  # this only changes the port visible in gitlab UI, not the actual listen port of SSH
        gitlab_rails['initial_root_password'] = "supersecret"
    ports:
      - '8929:8929'
      - '2424:22'  # ssh will run in port 22 unless changed in /asssets/sshd_config
    volumes:
      - 'gitlab-conf:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
      - ./fixtures/25_api_personal_access_token.rb:/opt/gitlab/embedded/service/gitlab-rails/ee/db/fixtures/production/025_api_personal_access_token.rb
      - ./fixtures/26_runner_token.rb:/opt/gitlab/embedded/service/gitlab-rails/ee/db/fixtures/production/026_runner_token.rb
    shm_size: '512m'
    healthcheck:
        test: ["CMD-SHELL", "curl --fail -si http://localhost:8929"]
        interval: 5s
        timeout: 1s
        retries: 3

  runner:
    image:  gitlab/gitlab-runner:ubuntu-v16.10.0
    volumes:
      - ./runner-conf:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  registry-backend:
    image: registry:2
    volumes:
      - registry_data:/var/lib/registry
      - ./registry-config:/etc/docker/registry
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3456/debug/health"]
        interval: 10s
        timeout: 1s
        retries: 3

  registry:
    image: joxit/docker-registry-ui:main
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - registry.local
    environment:
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=http://registry-backend:5000
      - REGISTRY_TITLE=Local
      - DELETE_IMAGES=true
    depends_on:
      - registry-backend
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80"]
        interval: 10s
        timeout: 1s
        retries: 3
