version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - ${PWD}/index.html:/usr/share/nginx/html/index.html
      - ${PWD}/conf:/etc/nginx/templates
    environment:
      - NGINX_PORT=8080
    ports:
      - 8888:8080
