ARG VERSION=3-alpine3.9
FROM python:${VERSION}
ARG PORT=9091
ENV FLASK_SERVER_PORT=$PORT

WORKDIR /src

COPY . .

RUN pip install -r requirements.txt --no-cache-dir

CMD [ "python", "server.py" ]

EXPOSE $PORT