pipeline {
    agent any
    environment {
        COMPOSE_DOCKER_CLI_BUILD = 1
        DOCKER_BUILDKIT          = 1
    }
    stages {
        stage('build') {
            steps {
                sh 'echo "this will build"'
            }
        }
        stage('test') {
            steps {
                sh '''
                    echo "this will test"
                '''
            }
        }
        stage('release') {
            steps {
                sh '''
                    echo "this will release"
                '''
            }
        }
    }
}
