FROM php:7.2-apache as backend

WORKDIR /root

RUN apt-get update && \
    apt-get install -y --no-install-recommends git zip
RUN curl --silent https://getcomposer.org/installer | php
RUN pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

COPY . .

RUN php /root/composer.phar install  \
    --ignore-platform-reqs \
    --no-ansi \
    --no-dev \
    --no-interaction \
    --no-scripts

FROM php:7.2-apache
RUN docker-php-ext-install pdo pdo_mysql

COPY --from=backend /var/www/html/ /var/www/html/
WORKDIR /var/www/html

COPY php.ini /usr/local/etc/php/php.ini