version: "3.0"
services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates/
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    ports:
      - 8000:80
    depends_on:
      - backend

  backend:
    image: my-flask
    build: flask
    environment:
      - FLASK_SERVER_PORT=9091
      - MONGO_DSN=mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes: 
      - db_data:/data/db

volumes:
  db_data: