FROM composer:2 as backend

WORKDIR /var/www/html

COPY . .

RUN composer install  \
    --ignore-platform-reqs \
    --no-ansi \
    --no-dev \
    --no-interaction \
    --no-scripts

FROM php:7.2-apache

RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

COPY php.ini /usr/local/etc/php/php.ini

COPY --from=backend /var/www/html/ /var/www/html/
RUN chmod -R 0777 /var/www/html/
