FROM composer:2.0.13 as backend

WORKDIR /app

COPY . /app/
RUN composer install  \
    --ignore-platform-reqs \
    --no-ansi \
    --no-dev \
    --no-interaction \
    --no-scripts

FROM php:7.2-apache

RUN pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install pdo pdo_mysql

COPY --from=backend /app /var/www/html/
COPY php.ini /usr/local/etc/php/php.ini