stages:
  - build

a_build:
  image: docker/compose
  stage: build
  services:
    - docker:20.10.13-dind
  variables:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: '1'
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
  script:
    - cd flask
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build backend
    - docker tag my-flask $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE
