stages:
  - build
  - test
  - release

a_build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
  script:
    - cd flask
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE

a_test:
  image: docker:19.03.12
  stage: test
  services:
    - name: docker:19.03.12-dind
      alias: localhost
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker run --rm -p 9090:9090 -d $CI_REGISTRY_IMAGE:latest
#    - [[ $( wget -O- -nv http://localhost:9090) == 'Hello from the MongoDB client!' ]]

a_release:
  stage: release
  script:
    - echo "this will release"
