pipeline {
    agent any
    environment {
        COMPOSE_DOCKER_CLI_BUILD = 1
        DOCKER_BUILDKIT          = 1
        SHORT_SHA                = """${sh(
                                    returnStdout: true,
                                    script: 'git rev-parse --short HEAD'
                                )}"""
    }
    stages {
        stage('build') {
            steps {
                sh '''
                    docker-compose build
                '''
            }
        }
        stage('test') {
            steps {
                sh 'docker-compose up -d'
                sh '[ "`curl -s http://docker:8000`" = "Hello from the MongoDB client!" ] && echo "it works!"'
            }
            post {
                always {
                    sh 'docker-compose down -v'
                }
            }
        }
        stage('release') {
            environment {
                REGISTRY                 = "registry.local"
                REGISTRY_CREDENTIALS     = credentials('docker-registry-local')
            }
            steps {
                sh 'docker login $REGISTRY -u $REGISTRY_CREDENTIALS_USR -p $REGISTRY_CREDENTIALS_PSW'
                sh 'docker tag my-flask $REGISTRY/my-flask:$SHORT_SHA'
                sh 'docker push $REGISTRY/my-flask:$SHORT_SHA'
                sh 'docker tag my-flask $REGISTRY/my-flask:latest'
                sh 'docker push $REGISTRY/my-flask:latest'
            }
        }
    }
}