FROM ruby:alpine as base

RUN apk add --no-cache libpq

RUN apk add --no-cache --virtual .build-deps \
  alpine-sdk \
  postgresql-dev \
  ruby-dev \
&& gem install pgsync

RUN apk del .build-deps

WORKDIR /sync

ENTRYPOINT [ "pgsync" ]