FROM ruby:alpine as base

RUN apk add --no-cache libpq \
&&  apk add --no-cache --virtual .build-deps \
  alpine-sdk \
  postgresql-dev \
  ruby-dev \
&& gem install pgsync \
&& apk del .build-deps

WORKDIR /sync

ENTRYPOINT [ "pgsync" ]