services: 
    registry:
      image: registry:2
      volumes:
        - registry_data:/var/lib/registry
        - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
        - ./registry-config/htpasswd:/etc/docker/registry/htpasswd
    ui:
      image: joxit/docker-registry-ui:2.5.2
      ports:
        - 80:80
      environment: 
        - SINGLE_REGISTRY=true
        - NGINX_PROXY_PASS_URL=http://registry:5000
        - REGISTRY_TITLE=Local
        - DELETE_IMAGES=true
      depends_on: 
        - registry

volumes: 
  registry_data: