pipeline {
    agent any
    environment {
        COMPOSE_DOCKER_CLI_BUILD = 1
        DOCKER_BUILDKIT          = 1
        REGISTRY_URL             = 'registry.local'
        REGISTRY_CREDENTIALS     = credentials('docker-registry-local')
    }
    stages {
        stage('build') {
            steps {
                sh '''
                    docker-compose build
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/bin/bash
                    docker-compose up -d
                    output=$(curl -s http://docker:8000)
                    docker-compose down
                    echo $output
                    [ "$output" == "Hello from the MongoDB client!" ] && echo 'It works!'
                '''
            }
        }
        stage('release') {
            steps {
                sh '''#!/bin/bash
                    docker login $REGISTRY_URL -u $REGISTRY_CREDENTIALS_USR -p $REGISTRY_CREDENTIALS_PSW
                    
                    docker tag my-flask $REGISTRY_URL/my-flask:${GIT_COMMIT:0:8}
                    docker tag my-flask $REGISTRY_URL/my-flask:latest
                    
                    docker push $REGISTRY_URL/my-flask:${GIT_COMMIT:0:8}
                    docker push $REGISTRY_URL/my-flask:latest
                '''
            }
        }
    }
}