FROM alpine:3.14.0 as compile

# Install compilation dependencies
RUN apk add g++

WORKDIR /src

COPY program.cpp ./

RUN g++ program.cpp -o prime && chmod +x prime

FROM alpine:3.14.0 as final

# Install runtime dependencies
RUN apk add libstdc++ 

COPY --from=compile /src/prime /

ENTRYPOINT [ "/prime" ]
