services:
  docker:
    image: docker:dind
    command: 
      - --insecure-registry
      - registry.local
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    healthcheck:
        test: ["CMD-SHELL", "docker ps"]
        interval: 10s
        timeout: 1s
        retries: 3

  executor:
    build: jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    healthcheck:
        test: ["CMD-SHELL", "curl -si http://127.0.0.1:8080"]
        interval: 10s
        timeout: 1s
        retries: 3

  registry-backend:
    image: registry:2
    volumes:
      - registry_data:/var/lib/registry
      - ./registry-config:/etc/docker/registry
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3456/debug/health"]
        interval: 10s
        timeout: 1s
        retries: 3

  registry:
    image: joxit/docker-registry-ui:main
    ports:
      - 80:80
    networks:
      default:
        aliases: 
          - registry.local
    environment: 
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=http://registry-backend:5000
      - REGISTRY_TITLE=Local
      - DELETE_IMAGES=true
    depends_on: 
      - registry-backend
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:80"]
        interval: 10s
        timeout: 1s
        retries: 3

  gogs:
    image: gogs/gogs:0.12.10
    ports:
      - "10022:22"
      - "3000:3000"
    volumes:
      - ./gogs/app.ini:/data/gogs/conf/app.ini
      - ./gogs/gogs.db:/data/gogs/data/gogs.db
    healthcheck:
        test: ["CMD-SHELL", "curl -si http://127.0.0.1:3000"]
        interval: 10s
        timeout: 1s
        retries: 3

volumes:
  registry_data:
  jenkins-docker-certs:
  jenkins-data:
  gogs-data: