# 2024-05-02 10:50
name: Test Gitlab infra
on:
  push:
    paths:
      - 'exercise-12/**'
      - '.github/workflows/test-gitlab-selfhosted.yml'
  schedule:
    - cron: '30 10 * * 1'

jobs:
  Test-run-gitlab-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start gitlab instance
        timeout-minutes: 5
        run: |
          cd ${GITHUB_WORKSPACE}/exercise-12/gitlab
          docker compose up -d

      - name: Configure git client
        run: |
          git config --global user.email "testbot@codium.team"
          git config --global user.name "Test Bot"

      - name: Wait for gitlab healthy
        timeout-minutes: 10
        run: |
          cd ${GITHUB_WORKSPACE}/exercise-12/gitlab
          . ./gitlab_helper.sh
          wait_for_gitlab_to_be_ready

      - name: Configure project and keys
        timeout-minutes: 2
        run: |
          cd ${GITHUB_WORKSPACE}/exercise-12/gitlab
          . ./gitlab_helper.sh
          wait_for_gitlab_to_be_ready  # wait again, as gitlab seems to restart the web server after first startup to reconfigure things
          create_ssh_key
          create_project

      - name: Create gitlab pipeline
        timeout-minutes: 3
        run: |
          cd ${GITHUB_WORKSPACE}/exercise-12/gitlab
          . ./gitlab_helper.sh
          configure_gitlab_git_ssh_command
          
          cd ${GITHUB_WORKSPACE}/exercise-12/1-python
          git init .
          git add .
          git commit -m "first commit"
          git remote add origin ssh://git@localhost:2424/root/exercise-12.git
          git push -u origin master
          
          wait_for_pipeline_job_created
