# 2024-05-02 10:50
name: Test Gitlab infra
on:
  push:
    paths:
      - 'exercise-12/*'
      - '.github/workflows/test-gitlab-selfhosted.yml'
  schedule:
    - cron: '30 10 * * 1'

jobs:
  Test-run-gitlab-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start gitlab instance
        timeout-minutes: 5
        run: |
          cd ${GITHUB_WORKSPACE}/exercise-12/gitlab
          docker compose up -d
      - name: Setup git
        run: |
          git config --global user.email "testbot@codium.team"
          git config --global user.name "Test Bot"
      - name: Wait for gitlab healthy
        timeout-minutes: 10
        run: |
          . gitlab_helper.sh
          wait_for_gitlab_to_be_ready
      - name: Create Jenkins pipeline
        timeout-minutes: 3
        run: |
          export EXERCISE_PATH=${GITHUB_WORKSPACE}/exercise-12
          cd ${EXERCISE_PATH}/gitlab
          . gitlab_helper.sh
          
          wait_for_gitlab_to_be_ready
          create_project
          create_ssh_key
          push_code
          wait_for_pipeline_job_created
